export let stateMenu = [
    { id: 1, text1: 'Abia' },
    { id: 2, text1: 'Adamawa' },
    { id: 3, text1: 'Akwa Ibom' },
    { id: 4, text1: 'Anambra' },
    { id: 5, text1: 'Bauchi' },
    { id: 6, text1: 'Bayelsa' },
    { id: 7, text1: 'Benue' },
    { id: 8, text1: 'Borno' },
    { id: 9, text1: 'Cross River' },
    { id: 10, text1: 'Delta' },
    { id: 11, text1: 'Ebonyi' },
    { id: 12, text1: 'Edo' },
    { id: 13, text1: 'Ekiti' },
    { id: 14, text1: 'Enugu' },
    { id: 15, text1: 'FCT - Abuja' },
    { id: 16, text1: 'Gombe' },
    { id: 17, text1: 'Imo' },
    { id: 18, text1: 'Jigawa' },
    { id: 19, text1: 'Kaduna' },
    { id: 20, text1: 'Kano' },
    { id: 21, text1: 'Katsina' },
    { id: 22, text1: 'Kebbi' },
    { id: 23, text1: 'Kogi' },
    { id: 24, text1: 'Kwara' },
    { id: 25, text1: 'Lagos' },
    { id: 26, text1: 'Nasarawa' },
    { id: 27, text1: 'Niger' },
    { id: 28, text1: 'Ogun' },
    { id: 29, text1: 'Ondo' },
    { id: 30, text1: 'Osun' },
    { id: 31, text1: 'Oyo' },
    { id: 32, text1: 'Plateau' },
    { id: 33, text1: 'Rivers' },
    { id: 34, text1: 'Sokoto' },
    { id: 35, text1: 'Taraba' },
    { id: 36, text1: 'Yobe' },
    { id: 37, text1: 'Zamfara' },
];
